name = "lean-classroom"
version = "0.1.0"
defaultTargets = ["lean-classroom"]

[[lean_lib]]
name = "LeanClassroom"

[[lean_exe]]
name = "lean-classroom"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0"